WebTestServer/Models/DatabaseModels.cs
using System.Globalization;
using System.Linq;
using Handler;
using Newtonsoft.Json;

namespace WebTest.Models
{
    public class LogItemModel
    {
        public string DT   { get; }
        public string Host { get; }
        public string Data { get; }

        public LogItemModel(DBLogItem p)
        {
            DT   = p.dt.ToString("dd.MM.yyyy HH:mm:ss");
            Host = p.host;

            var m = JsonConvert.DeserializeObject<ResponseModel>(p.data);
            Data = string.Join(
                ", ", m.Data?.Select(d => "<span class='code'>" + d.Code + "</span>=<span class='value'>" + d.Value.ToString("F2", CultureInfo.InvariantCulture) + "</span>"));
        }
    }
}

WebTestServer/Models/ErrorViewModel.cs
using System;

#pragma warning disable CS8618

namespace WebTest.Models
{
    public class ErrorViewModel
    {
        public string RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

WebTestServer/Models/HomeModels.cs
using System.Collections.Generic;

#pragma warning disable CS8618

namespace WebTest.Models
{
    public class HomeIndexModel
    {
        public Dictionary<string, string> Env            { get; set; }
        public NetworkInterfaceItem[]     Interfaces     { get; set; }
        public Dictionary<string, string> RequestHeaders { get; set; }
    }

    public class NetworkInterfaceItem
    {
        public string Name      { get; set; }
        public string Addresses { get; set; }
    }
}

WebTestServer/Controllers/DatabaseController.cs
using System.Linq;
using Handler;
using Microsoft.AspNetCore.Mvc;
using WebTest.Models;

namespace WebTest.Controllers
{
    public class DatabaseController : Controller
    {
        readonly IDatabaseHandler db;

        public DatabaseController(IDatabaseHandler db) => this.db = db;

        public IActionResult Index()
        {
            var items = db.GetLast(100).Select(p => new LogItemModel(p)).ToArray();
            return View(items);
        }
    }
}

WebTestServer/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Net.NetworkInformation;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using WebTest.Models;

namespace WebTest.Controllers
{
    public class HomeController : Controller
    {
        readonly ILogger<HomeController> logger;

        public HomeController(ILogger<HomeController> logger) => this.logger = logger;

        public IActionResult Index()
        {
            var envs = Environment.GetEnvironmentVariables();

            var m = new HomeIndexModel() { Env = new Dictionary<string, string>() };
            foreach (var key in envs.Keys.OfType<string>())
                m.Env.Add(key, envs[key]!.ToString()!);

            m.RequestHeaders = Request.Headers.ToDictionary(p => p.Key, p => p.Value.ToString());
            m.Interfaces = NetworkInterface.GetAllNetworkInterfaces()
                                           .Select(p =>
                                           {
                                               var a = p.GetIPProperties().UnicastAddresses;
                                               return new NetworkInterfaceItem()
                                               {
                                                   Name      = p.Name + ": " + p.NetworkInterfaceType,
                                                   Addresses = !a.Any() ? "-" : string.Join("<br/>", a.Select(add => add.Address.ToString()))
                                               };
                                           })
                                           .ToArray();
            return View(m);
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

WebTestServer/Controllers/LocalController.cs
using System;
using System.Diagnostics;
using System.Threading;
using System.Threading.Tasks;
using Handler;
using Microsoft.AspNetCore.Mvc;
using Newtonsoft.Json;

namespace WebTest.Controllers
{
    public class LocalController : Controller
    {
        readonly CoursesHandler ch;
        readonly MetricHandler  mh;

        public LocalController(CoursesHandler ch, MetricHandler mh)
        {
            this.ch = ch;
            this.mh = mh;
        }

        public IActionResult Index() => View();

        public async Task<ResponseModel> GetCourse(string ids, [FromServices] IDatabaseHandler db)
        {
            switch (ids)
            {
                case "crash":
                    Environment.Exit(-1);
                    break;
              
                case "500":
                    throw new InvalidOperationException("FAILED INPUT");
            }
            
            var sw = Stopwatch.StartNew();
            Thread.Sleep(new Random().Next(200));
            try
            {
                var _ids   = ids.Split(',', StringSplitOptions.RemoveEmptyEntries | StringSplitOptions.TrimEntries);
                var result = new ResponseModel(await ch.Get(_ids), Request.Headers);

                mh.Set(MetricHandler.LocalItemsCount, result.Data.Length);
                mh.Increment(MetricHandler.LocalRequestSuccess);
                mh.Increment(MetricHandler.LocalRequestCount);
                mh.Set(MetricHandler.LocalRequestDuration, sw.ElapsedMilliseconds);

                db.Put(new DBLogItem()
                {
                    data = JsonConvert.SerializeObject(result),
                    host = "LOCAL",
                    dt   = DateTime.UtcNow
                });
                
                return result;
            }
            catch (Exception e)
            {
                mh.Increment(MetricHandler.LocalRequestFailed);
                return new ResponseModel((e.InnerException ?? e).Message, Request.Headers);
            }
            finally
            {
                sw.Stop();
            }
        }
    }
}

WebTestServer/Controllers/RemoteController.cs
using System;
using System.Diagnostics;
using System.Net.Http;
using System.Net.Http.Json;
using System.Threading.Tasks;
using Handler;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Configuration;

#pragma warning disable CS8603

namespace WebTest.Controllers
{
    public class RemoteController : Controller
    {
        readonly string        RemoteHostName;
        readonly MetricHandler mh;

        public RemoteController(IConfiguration config, MetricHandler mh)
        {
            RemoteHostName = config["WebTestServiceAddress"];
            this.mh        = mh;
        }

        public IActionResult Index() => View();

        public async Task<ResponseModel> GetCourse(string ids)
        {
            var       sw     = Stopwatch.StartNew();
            using var client = new HttpClient();
            client.Timeout = TimeSpan.FromSeconds(3);
            try
            {
                var r = await client.GetFromJsonAsync<ResponseModel>(RemoteHostName + "/Home/GetCourse?ids=" + ids);
                if (!r!.Success)
                {
                    r.Error = "Error from remote service: " + r.Error;
                }

                mh.Set(MetricHandler.RemoteItemsCount, r.Data.Length);
                mh.Increment(MetricHandler.RemoteRequestSuccess);
                mh.Increment(MetricHandler.RemoteRequestCount);
                mh.Set(MetricHandler.RemoteRequestDuration, sw.ElapsedMilliseconds);

                return r;
            }
            catch (Exception e)
            {
                mh.Increment(MetricHandler.RemoteRequestFailed);
                return new ResponseModel((e.InnerException ?? e).Message, Request.Headers);
            }
            finally
            {
                sw.Stop();
            }
        }
    }
}

WebTestServer/Views/Database/Index.cshtml
@{
    ViewData["Title"] = "Local";
}
@model LogItemModel[]
<style>
    th.c, td.c { text-align: center }
    th,td { padding: 2px 6px; }
    span.code { }
    span.value { color: blue; }
</style>

<div class="row">
    <div class="col col-12">
        <table>
            <tr>
                <th style="width:12em" class="c">Date/Time (UTC)</th>
                <th style="width:20em">Host</th>
                <th>Data</th>
            </tr>
            @foreach (var m in Model)
            {
                <tr>
                    <td class="c">@m.DT</td>
                    <td>@m.Host</td>
                    <td>@Html.Raw(m.Data)</td>
                </tr>
            }
        </table>
    </div>
</div>

WebTestServer/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
    var p = Process.GetCurrentProcess();
}
@using System.Diagnostics
@model HomeIndexModel

<div class="row">
    <div class="col col-4">
        <table>
            <tr>
                <th colspan="2">System information</th>
            </tr>
            <tr>
                <td>Host name</td>
                <td>@Environment.GetEnvironmentVariable("COMPUTERNAME")</td>
            </tr>
            <tr>
                <td>ProcessorCount</td>
                <td>@Environment.ProcessorCount</td>
            </tr>
            <tr>
                <td>GC.GetTotalMemory</td>
                <td>@(GC.GetTotalMemory(false) / 1048576) MB</td>
            </tr>
            <tr>
                <td>VirtualMemory</td>
                <td>@(p.VirtualMemorySize64 / 1048576) MB</td>
            </tr>
            <tr>
                <td>MaxWorkingSet</td>
                <td>@(p.MaxWorkingSet.ToInt64() / 1024) KB</td>
            </tr>
            <tr>
                <td>WorkingSet</td>
                <td>@(p.WorkingSet64 / 1048576) MB</td>
            </tr>
        </table>
        
        <table class="mt-2">
            <tr>
                <th colspan="2">Network interfaces</th>
            </tr>
            @foreach (var key in Model.Interfaces)
            {
                <tr>
                    <td>@key.Name</td>
                    <td>
                        <pre>@Html.Raw(key.Addresses)</pre>
                    </td>
                </tr>
            }
        </table>
    </div>

    <div class="col col-8">
            <table>
                <tr>
                    <th colspan="2">Request headers</th>
                </tr>
                @foreach (var key in Model.RequestHeaders)
                {
                    <tr>
                        <td style="width: 20em">@key.Key</td>
                        <td>@Html.Raw(key.Value)</td>
                    </tr>
                }
            </table>
        </div>
</div>

<div class="row mt-2">
    <div class="col col-12">
        <table>
            <tr>
                <th colspan="2">Environment variables</th>
            </tr>
            @foreach (var key in Model.Env.OrderBy(p => p.Key))
            {
                <tr>
                    <td style="width: 20em">@key.Key</td>
                    <td>@key.Value</td>
                </tr>
            }
        </table>
    </div>
</div>

WebTestServer/Views/Local/Index.cshtml
@{
    ViewData["Title"] = "Local";
}
@model Handler.ResponseModel

<div class="row">
    <div class="col col-4">
        <div>
            <form>
                <label>Valute codes (comma-separated)</label>
                <input type="text" style="width:100%;" value="USD,EUR,GBP,CHF"/>
                <a href="#" class="mt-1 btn btn-primary">Get</a><span class="hidden ml-2 waiting">Waiting....</span>
            </form>
        </div>
        
        <div class="alert alert-primary mt-1 hidden" role="alert"></div>
        <div class="alert alert-danger mt-1 hidden" role="alert"></div>
    </div>
</div>
<div class="row mt-1">
    <div class="col col-12 data"></div>
</div>

<div class="row mt-1">
    <div class="col col-12 headers"></div>
</div>

<script>
$("a").click(function () {
    getResponse('@Url.Action("GetCourse")');
});
</script>

WebTestServer/Views/Remote/Index.cshtml
@{
    ViewData["Title"] = "Remote";
}
@model Handler.ResponseModel

<div class="row">
    <div class="col col-4">
        <div>
            <form>
                <label>Valute codes (comma-separated)</label>
                <input type="text" style="width:100%;" value="USD,EUR,GBP,CHF"/>
                <a href="#" class="mt-1 btn btn-primary">Get</a><span class="hidden ml-2 waiting">Waiting....</span>
            </form>
        </div>
        
        <div class="alert alert-primary mt-1 hidden" role="alert"></div>
        <div class="alert alert-danger mt-1 hidden" role="alert"></div>
    </div>
</div>
<div class="row mt-1">
    <div class="col col-12 data"></div>
</div>

<div class="row mt-1">
    <div class="col col-12 headers"></div>
</div>

<script>
$("a").click(function () {
    getResponse('@Url.Action("GetCourse")');
});
</script>

WebTestServer/Views/Shared/_Layout.cshtml
@using Microsoft.Extensions.DependencyInjection
@using Handler
@{
    var dbEnabled = ViewContext.HttpContext.RequestServices.GetRequiredService<IDatabaseHandler>().Enabled;
}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8"/>
    <meta name="viewport" content="width=device-width, initial-scale=1.0"/>
    <title>@ViewData["Title"] - WebTestServer</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css"/>
    <link rel="stylesheet" href="~/css/site.css"/>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/site.js"></script>
</head>
<body>
<header>
    <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
        <div class="container">
            <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                <ul class="navbar-nav flex-grow-1">
                    <li class="nav-item">
                        <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                    </li>

                    <li class="nav-item">
                        <a class="nav-link text-dark" asp-area="" asp-controller="Local" asp-action="Index">Local</a>
                    </li>

                    <li class="nav-item">
                        <a class="nav-link text-dark" asp-area="" asp-controller="Remote" asp-action="Index">Remote</a>
                    </li>
                    @if (dbEnabled)
                    {
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Database" asp-action="Index">Request log</a>
                        </li>
                    }
                </ul>
            </div>
        </div>
    </nav>
</header>

<div class="container-fluid">
    @RenderBody()
</div>

@await RenderSectionAsync("Scripts", required: false)
</body>
</html>